CREATE DATABASE IF NOT EXISTS Employee;
USE Employee;

-- Create Employee Table
CREATE TABLE employee_details (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(20),
    SALARY DECIMAL(10,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT
);

-- Create Department Table
CREATE TABLE department_details (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100),
    MANAGER_ID INT,
    LOCATION_ID INT
);

SHOW VARIABLES LIKE 'secure_file_priv';

CREATE TABLE employee_details_temp (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE VARCHAR(20),
    JOB_ID VARCHAR(20),
    SALARY DECIMAL(10,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT
    );


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/employee_details.csv'
INTO TABLE employee_details_temp
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

INSERT INTO employee_details (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, 
HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID)
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, 
PHONE_NUMBER, STR_TO_DATE(HIRE_DATE, '%d-%m-%Y'), JOB_ID,
SALARY, MANAGER_ID, DEPARTMENT_ID
FROM employee_details_temp;

DROP TABLE employee_details_temp;

select * from employee_details;

SELECT MANAGER_ID, FIRST_NAME, LAST_NAME, SALARY
FROM employee_details e1
WHERE SALARY = (SELECT MIN(SALARY) FROM employee_details e2 WHERE e1.MANAGER_ID = e2.MANAGER_ID);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, COUNT(*)
FROM employee_details
GROUP BY EMPLOYEE_ID, FIRST_NAME, LAST_NAME
HAVING COUNT(*) > 1;

SELECT FIRST_NAME, REPLACE(FIRST_NAME, 'a', 'A') AS MODIFIED_NAME
FROM employee_details;

SELECT * FROM employee_details
WHERE YEAR(HIRE_DATE) = 2002 AND MONTH(HIRE_DATE) = 8
ORDER BY HIRE_DATE;

SELECT * FROM employee_details
WHERE HIRE_DATE < '2010-02-04';

SELECT * FROM employee_details
WHERE SALARY BETWEEN 40000 AND 60000;





